### ISSUE TITLE
`no_std` support

### ISSUE THREAD

**Issue by japaric** [steveklabnik/ref_slice#4]
I can send a PR but what's the convention for `no_std` support? An opt-out `std` feature or an opt-in `no_std` feature?

**Comment by steveklabnik** [comment]
Is there any reason to not just make it always `no_std`? That'd still work with std-enabled programs, and it's not like I'm ever going to really use std features in this crate.

**Comment by japaric** [comment]
Oh right, that makes sense.

**Comment by steveklabnik** [comment]
This has been fixed! https://github.com/steveklabnik/ref_slice/blob/master/src/lib.rs#L1
